//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiInteligente2022.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiInteligente2022.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        internal static string AboutAppVersion {
            get {
                return ResourceManager.GetString("AboutAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string AboutDeviceModel {
            get {
                return ResourceManager.GetString("AboutDeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        internal static string AboutDeviceName {
            get {
                return ResourceManager.GetString("AboutDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Platform.
        /// </summary>
        internal static string AboutDevicePlatform {
            get {
                return ResourceManager.GetString("AboutDevicePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Versión.
        /// </summary>
        internal static string AboutDeviceSystemVersion {
            get {
                return ResourceManager.GetString("AboutDeviceSystemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string AboutManufacturer {
            get {
                return ResourceManager.GetString("AboutManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string BranchDetailTitle {
            get {
                return ResourceManager.GetString("BranchDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        internal static string CurrentLocationLabel {
            get {
                return ResourceManager.GetString("CurrentLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting location.
        /// </summary>
        internal static string GetLocationErrorTitle {
            get {
                return ResourceManager.GetString("GetLocationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device has no geolocation enabled.
        /// </summary>
        internal static string GetLocationNotEnabledError {
            get {
                return ResourceManager.GetString("GetLocationNotEnabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device does not support geolocation.
        /// </summary>
        internal static string GetLocationNotSupportedError {
            get {
                return ResourceManager.GetString("GetLocationNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission for geolocation required.
        /// </summary>
        internal static string GetLocationPermissionError {
            get {
                return ResourceManager.GetString("GetLocationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguagePageSubtitle {
            get {
                return ResourceManager.GetString("LanguagePageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Language.
        /// </summary>
        internal static string LanguagePageTitle {
            get {
                return ResourceManager.GetString("LanguagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show route.
        /// </summary>
        internal static string LocationShowRoute {
            get {
                return ResourceManager.GetString("LocationShowRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        internal static string LocationsTitle {
            get {
                return ResourceManager.GetString("LocationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during login. Please check your credentials.
        /// </summary>
        internal static string LoginAlertError {
            get {
                return ResourceManager.GetString("LoginAlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        internal static string LoginPageSignUpButton {
            get {
                return ResourceManager.GetString("LoginPageSignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must write a password.
        /// </summary>
        internal static string LoginPasswordError {
            get {
                return ResourceManager.GetString("LoginPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("LoginPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string LoginSubtitle {
            get {
                return ResourceManager.GetString("LoginSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginUserAlertTitle {
            get {
                return ResourceManager.GetString("LoginUserAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must write a user name.
        /// </summary>
        internal static string LoginUserError {
            get {
                return ResourceManager.GetString("LoginUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string LoginUserPlaceHolder {
            get {
                return ResourceManager.GetString("LoginUserPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string MainMenuLocations {
            get {
                return ResourceManager.GetString("MainMenuLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MainMenuLogout {
            get {
                return ResourceManager.GetString("MainMenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Report.
        /// </summary>
        internal static string MainMenuNewReport {
            get {
                return ResourceManager.GetString("MainMenuNewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string MainMenuReports {
            get {
                return ResourceManager.GetString("MainMenuReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option.
        /// </summary>
        internal static string MainMenuSubtitle {
            get {
                return ResourceManager.GetString("MainMenuSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string MainMenuSync {
            get {
                return ResourceManager.GetString("MainMenuSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidences.
        /// </summary>
        internal static string NewReportStep1Subtitle {
            get {
                return ResourceManager.GetString("NewReportStep1Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Information.
        /// </summary>
        internal static string NewReportStep2Subtitle {
            get {
                return ResourceManager.GetString("NewReportStep2Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Report.
        /// </summary>
        internal static string NewReportTitle {
            get {
                return ResourceManager.GetString("NewReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string PinLabelDestination {
            get {
                return ResourceManager.GetString("PinLabelDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string PreviewPhotoSubtitle {
            get {
                return ResourceManager.GetString("PreviewPhotoSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string ProgressBarHeader {
            get {
                return ResourceManager.GetString("ProgressBarHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount.
        /// </summary>
        internal static string ReportAmount {
            get {
                return ResourceManager.GetString("ReportAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client city.
        /// </summary>
        internal static string ReportClientCity {
            get {
                return ResourceManager.GetString("ReportClientCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client country.
        /// </summary>
        internal static string ReportClientCountry {
            get {
                return ResourceManager.GetString("ReportClientCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client information.
        /// </summary>
        internal static string ReportClientDetailsHeader {
            get {
                return ResourceManager.GetString("ReportClientDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID document.
        /// </summary>
        internal static string ReportClientDocument {
            get {
                return ResourceManager.GetString("ReportClientDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID document number.
        /// </summary>
        internal static string ReportClientDocumentNumber {
            get {
                return ResourceManager.GetString("ReportClientDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client email.
        /// </summary>
        internal static string ReportClientEmail {
            get {
                return ResourceManager.GetString("ReportClientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name.
        /// </summary>
        internal static string ReportClientName {
            get {
                return ResourceManager.GetString("ReportClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client number.
        /// </summary>
        internal static string ReportClientNumber {
            get {
                return ResourceManager.GetString("ReportClientNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client phone number.
        /// </summary>
        internal static string ReportClientPhone {
            get {
                return ResourceManager.GetString("ReportClientPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report details.
        /// </summary>
        internal static string ReportDetail {
            get {
                return ResourceManager.GetString("ReportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Details.
        /// </summary>
        internal static string ReportDetailsHeader {
            get {
                return ResourceManager.GetString("ReportDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string ReportPhotosHeader {
            get {
                return ResourceManager.GetString("ReportPhotosHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake photo.
        /// </summary>
        internal static string RetakePhotoButton {
            get {
                return ResourceManager.GetString("RetakePhotoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string SignUpAddressPlaceholder {
            get {
                return ResourceManager.GetString("SignUpAddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during user creation.
        /// </summary>
        internal static string SignUpAlertErrorUserCreation {
            get {
                return ResourceManager.GetString("SignUpAlertErrorUserCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was created successfully.
        /// </summary>
        internal static string SignUpAlertSuccessUserCreation {
            get {
                return ResourceManager.GetString("SignUpAlertSuccessUserCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string SignUpCreateButton {
            get {
                return ResourceManager.GetString("SignUpCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Credentials.
        /// </summary>
        internal static string SignUpCredentials {
            get {
                return ResourceManager.GetString("SignUpCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string SignUpEmailPlaceholder {
            get {
                return ResourceManager.GetString("SignUpEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must write an address.
        /// </summary>
        internal static string SignUpInvalidAddressMessage {
            get {
                return ResourceManager.GetString("SignUpInvalidAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must write a valid email.
        /// </summary>
        internal static string SignUpInvalidEmailMessage {
            get {
                return ResourceManager.GetString("SignUpInvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must meet the following requirements:
        ///- At least 1 lowercase
        ///- At least 1 uppercase
        ///- At least 1 number
        ///- At least 1 special character @$!%*?&amp;
        ///- The minimum length is 8 characters.
        /// </summary>
        internal static string SignUpInvalidPasswordMessage {
            get {
                return ResourceManager.GetString("SignUpInvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number must have the format +521234567890.
        /// </summary>
        internal static string SignUpInvalidPhoneMessage {
            get {
                return ResourceManager.GetString("SignUpInvalidPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must write a user name.
        /// </summary>
        internal static string SignUpInvalidUserNameMessage {
            get {
                return ResourceManager.GetString("SignUpInvalidUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignUpPasswordPlaceholder {
            get {
                return ResourceManager.GetString("SignUpPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Personal Info.
        /// </summary>
        internal static string SignUpPersonalData {
            get {
                return ResourceManager.GetString("SignUpPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string SignUpPhonePlaceholder {
            get {
                return ResourceManager.GetString("SignUpPhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        internal static string SignUpSubtitle {
            get {
                return ResourceManager.GetString("SignUpSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        internal static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        internal static string SignUpUserAlertTitle {
            get {
                return ResourceManager.GetString("SignUpUserAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string SignUpUserPlaceholder {
            get {
                return ResourceManager.GetString("SignUpUserPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string SplashWelcome {
            get {
                return ResourceManager.GetString("SplashWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree Terms and Conditions.
        /// </summary>
        internal static string TermsAcceptButton {
            get {
                return ResourceManager.GetString("TermsAcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conditions.
        /// </summary>
        internal static string TermsPageTitle {
            get {
                return ResourceManager.GetString("TermsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value must be a valid email.
        /// </summary>
        internal static string ValidationsEmail {
            get {
                return ResourceManager.GetString("ValidationsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value must be a {0} characters value.
        /// </summary>
        internal static string ValidationsExactLength {
            get {
                return ResourceManager.GetString("ValidationsExactLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value must be greater than {0}.
        /// </summary>
        internal static string ValidationsGreater {
            get {
                return ResourceManager.GetString("ValidationsGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value must have less than {0} characters.
        /// </summary>
        internal static string ValidationsMaxLength {
            get {
                return ResourceManager.GetString("ValidationsMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must have a value.
        /// </summary>
        internal static string ValidationsNull {
            get {
                return ResourceManager.GetString("ValidationsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value must be a valid phone number.
        /// </summary>
        internal static string ValidationsPhone {
            get {
                return ResourceManager.GetString("ValidationsPhone", resourceCulture);
            }
        }
    }
}
